apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: xraydaemon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xraydaemon
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80